apiVersion: opentofu.upbound.io/v1beta1
kind: Workspace
metadata:
  name: vault
  annotations:
spec:
  forProvider:
    env:
      - name: TF_VAR_compartment_id
        value: ocid1.tenancy.oc1..aaaaaaaaour4bncy5qvbtjv74iiyvdc6bbibwj6nbdahkyhziez5bqkp45aq
      - name: TF_VAR_display_name
        value: vault
      - name: TF_VAR_vault_type
        value: DEFAULT
    module: git::https://github.com/PZoli98/terraform-modules.git//vault?ref=main
    source: Remote
  providerConfigRef:
    name: opentofu-providerconfig
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: vault-config
