on:
  workflow_dispatch

jobs:
  policy-check:
    runs-on: ubuntu-latest
    name: Check policies
    steps:
      - name: Install Kyverno CLI
        uses: kyverno/action-install-cli@v0.2.0
        with:
          release: 'v1.9.5'

      - name: Get repo
        uses: actions/checkout@v4
        with:
          path: infra

      - name: Get policies
        uses: actions/checkout@v4
        with:
          repository: https://github.com/PZoli98/platform-policies.git
          path: platform-policies
          
      - name: Apply policies
        working-directory: infra/oracle-db-test
        run: |
          for manifest in *.yaml; do
            kyverno apply ../../platform-policies/application-policy.yaml -r "$manifest" -p
          done
